// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlv26ylqDSPZItOSf8pHAx1U5Kkb6Iu9A',
    appId: '1:966003121254:web:1b20db8a651401fc7021a7',
    messagingSenderId: '966003121254',
    projectId: 'myibd-63c58',
    authDomain: 'myibd-63c58.firebaseapp.com',
    storageBucket: 'myibd-63c58.firebasestorage.app',
    measurementId: 'G-TQNPNT40SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvP3J69RUbIyxMm-QXgssvDxsYFmEKw48',
    appId: '1:966003121254:android:8c7a2ed647575baa7021a7',
    messagingSenderId: '966003121254',
    projectId: 'myibd-63c58',
    storageBucket: 'myibd-63c58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbnXrBFxlX96LJhS4-WOp7BH75bfQpZlc',
    appId: '1:966003121254:ios:fab8ff794e88173a7021a7',
    messagingSenderId: '966003121254',
    projectId: 'myibd-63c58',
    storageBucket: 'myibd-63c58.firebasestorage.app',
    iosBundleId: 'com.example.myibdApp',
  );
}
